version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - /vagrant/config.alloy:/etc/alloy/config.alloy
      
  prometheus: 
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /vagrant/prometheus.yml:/etc/prometheus/prometheus.yml
  